apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-a-dev
  namespace: argocd
spec:
  project: helm-guestbook-a
  source:
    repoURL: https://h.cfcr.io/codefreshdemo/demo
    chart: helm-guestbook
    targetRevision: 0.1.5
  destination:
    server: https://kubernetes.default.svc
    namespace: dev